[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN101",
    "C901",
    "COM812",
    "D107",
    "D203",
    "D213",
    "D415",
    "E501",
    "ERA001",
    "PLR09",
    "PLR1722",
    "T20",
]

[tool.ruff.lint.per-file-ignores]
"*_test.py" = ["S101", "D101", "D102", "D103", "ANN201"]
"abc.py" = ["D102"]

[tool.isort]
profile = "black"
